name: Build and Test

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
  lint:
    name: Check linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
      - name: Upgrade and install tools
        run: |
          python -m pip install -U uv
          python -m uv pip install -U hatch
          python -m hatch env create default
      - name: Set PY
        run: echo "PY=$(hatch run gh-cache-sum)" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}
      - name: Run lint checks
        run: hatch run check

  build-install:
    name: Test package build and installation
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      fail-fast: true
      matrix:
        hatch-env: [default, sa14]
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Setup up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
      - name: Upgrade and install tools
        run: |
          python -m pip install -U uv
          python -m uv pip install -U hatch
      - name: Build package
        run: |
          python -m hatch -e ${{ matrix.hatch-env }} build --clean
      - name: Install and check import
        run: |
          python -m uv pip install dist/snowflake_sqlalchemy-*.whl
          python -c "import snowflake.sqlalchemy; print(snowflake.sqlalchemy.__version__)"

